
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcwgtxmzfudslcfrjte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY3dndHhtemZ1ZHNsY2ZyanRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NjA2MTYsImV4cCI6MjA1NDUzNjYxNn0.0Hqah1sZxTI2V6eSzCTzctua2T144Fg4jjfpJcaN9FU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
